### Advanced Collections

### namedtuple
#### factory function for creating tuple subclasses with named fields

In [6]:
from collections import namedtuple 
Employee = namedtuple('Employee', 'name title location')
emp1 = Employee(name="Zahid", title="Cool Guy!", location="Boston")
print(emp1.name)
print(emp1[2])   # access by index

emp2 = Employee(name="Dave", title="Cool Guy!", location="Los Angeles")
print(emp2.name)
print(emp2[2])   # access by index

Zahid
Boston
Dave
Los Angeles


#### Counter
##### Counts number of ocurrances of each element

In [2]:
from collections import Counter
l = [1, 1, 1, 2,2, 3, 4, 5,5,5,5,5,6,7,7]
Counter(l)

Counter({1: 3, 2: 2, 3: 1, 4: 1, 5: 5, 6: 1, 7: 2})

In [9]:
s = "hello world, how are you doing?"
Counter(s)

Counter({'h': 2,
         'e': 2,
         'l': 3,
         'o': 5,
         ' ': 5,
         'w': 2,
         'r': 2,
         'd': 2,
         ',': 1,
         'a': 1,
         'y': 1,
         'u': 1,
         'i': 1,
         'n': 1,
         'g': 1,
         '?': 1})

In [4]:
s = """
A man was painting a new sign for a pub called the Pig and Whistle.
The landlord said, "You haven't left enough space between Pig and and and and and Whistle.
"""

words = s.split()
Counter(words)

Counter({'A': 1,
         'man': 1,
         'was': 1,
         'painting': 1,
         'a': 2,
         'new': 1,
         'sign': 1,
         'for': 1,
         'pub': 1,
         'called': 1,
         'the': 1,
         'Pig': 2,
         'and': 6,
         'Whistle.': 2,
         'The': 1,
         'landlord': 1,
         'said,': 1,
         '"You': 1,
         "haven't": 1,
         'left': 1,
         'enough': 1,
         'space': 1,
         'between': 1})

In [5]:
c = Counter(words)
c.most_common(3)

[('and', 6), ('a', 2), ('Pig', 2)]

In [21]:
c = Counter(sorted("aabbbccde"))
# c.most_common(3)
#[print(a,b) for a,b in c.most_common(3)]
for x in c.most_common(3):
    print(*x)


b 3
a 2
c 2


#### defaultdict
##### dict subclass that calls a factory function to supply missing values

In [15]:
from collections import defaultdict

In [16]:
# normal dict
d= {'k': 1}
d['k2'] # generates an error

KeyError: 'k2'

In [19]:
d = defaultdict(int) # default value 
d['one']  # since default is int, the default value for a new key will be 0

0

In [23]:
d = defaultdict(str)
d["one"]

''

In [24]:
# assign lambda function
d = defaultdict(lambda : "n/a")  # default value will be "n/a"
d["one"]

'n/a'

### OrderedDict
#### dict subclass that remembers the order entries were added

In [34]:
# normal dictionary
d = {}
d['a'] = 1
d['b'] = 4
d['c'] = 2
d['d'] = 3
d['e'] = 4

for k,v in d.items():
    print(k,v)
    
# Note: python 3.7+ now retain insertion order

a 1
b 4
c 2
d 3
e 4


In [30]:
# OrderedDict dictionary
from collections import OrderedDict
d = OrderedDict()
d['a'] = 1
d['b'] = 4
d['c'] = 2
d['d'] = 3
d['e'] = 4

for k,v in d.items():
    print(k,v)

a 1
b 4
c 2
d 3
e 4


#### deque
##### list-like container with fast appends and pops on either end

In [53]:
from collections import deque
d = deque("hello")
for s in d:
    print(s.upper())

H
E
L
L
O


In [48]:
d.append('z')
d

deque(['h', 'e', 'l', 'l', 'o', 'z'])

In [49]:
d.appendleft('a')
d

deque(['a', 'h', 'e', 'l', 'l', 'o', 'z'])

In [50]:
d.pop()
d

deque(['a', 'h', 'e', 'l', 'l', 'o'])

In [51]:
d.popleft()
d

deque(['h', 'e', 'l', 'l', 'o'])

In [54]:
d.rotate(2) # rotate elements by 2
d

deque(['l', 'o', 'h', 'e', 'l'])

In [55]:
d.extendleft('123')  # NOTE: 1, then 2, then 3 
d

deque(['3', '2', '1', 'l', 'o', 'h', 'e', 'l'])

In [32]:
import numpy
s = input()
x = map(int,s.split())
print(str(numpy.eye(*x)).replace('1',' 1').replace('0',' 0'))

 5 4


[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  0.]]


In [ ]:
print(str(numpy.eye(*map(int,input().split()))).replace('1',' 1').replace('0',' 0'))

In [31]:
print(*map(int,s.split()))


5 4
